services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: ssr_dp_2025_db
    environment:
      POSTGRES_DB: ssr_dp_2025
      POSTGRES_USER: ssr_dp_2025_user
      POSTGRES_PASSWORD: supsersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - donation_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ssr_dp_2025_user -d ssr_dp_2025"]
      interval: 60s
      timeout: 5s
      retries: 5

  # Combined Frontend and Backend Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssr_dp_2025_app
    environment:
      DATABASE_URL: postgresql://ssr_dp_2025_user:supsersecret@db:5432/ssr_dp_2025
      SECRET_KEY: your-secret-key-change-in-production
      JWT_SECRET_KEY: jwt-secret-key-change-in-production
      FLASK_ENV: production
      VITE_API_URL: http://localhost/api/v1
    ports:
      - "80:80"
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - donation_network
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend

volumes:
  postgres_data:

networks:
  donation_network:
    driver: bridge
