services:
  # Web Application Service Only
  # Note: Create PostgreSQL database manually in Render dashboard
  - type: web
    name: donation-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.production
    dockerContext: .
    dockerCommand: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        cd /app/backend &&
        python wait_for_db.py &&
        echo 'Initializing database...' &&
        python init_db.py &&
        echo 'Adding users...' &&
        python add_multiple_users.py &&
        echo 'Running comprehensive verification...' &&
        python verify_setup.py &&
        echo 'Starting combined application...' &&
        /app/start.sh
      "
    envVars:
      - key: DATABASE_URL
        value: postgresql://user:password@host:5432/database
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: VITE_API_URL
        value: https://donation-app.onrender.com/api/v1
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - Dockerfile.production
        - .dockerignore
    healthCheckPath: /health
    autoDeploy: true
