services:
  # Web Application Service Only
  # Note: Create PostgreSQL database manually in Render dashboard
  - type: web
    name: donation-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.production
    dockerContext: .
    startCommand: bash /app/start.sh

    envVars:
      - key: DATABASE_URL
        value: postgresql://user:password@host:5432/database
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: VITE_API_URL
        value: https://donation-app-1wvv.onrender.com/api/v1
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - Dockerfile.production
        - .dockerignore
    healthCheckPath: /health
    autoDeploy: true
    # Force clean deployment
